import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#406d58",
        "surface-container": "#f2ede4",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#a33e16",
        "on-primary-container": "#fff1ee",
        "surface-container-lowest": "#ffffff",
        "primary": "#99370f",
        "secondary-fixed": "#bceed3",
        "on-secondary-fixed-variant": "#224f3c",
        "inverse-on-surface": "#f5f0e7",
        "error-container": "#ffdad6",
        "outline": "#8a726a",
        "on-primary-fixed": "#390c00",
        "on-background": "#1d1c16",
        "outline-variant": "#dec0b7",
        "inverse-primary": "#ffb59c",
        "primary-container": "#ba4e26",
        "on-surface-variant": "#57423b",
        "on-tertiary-container": "#fff1e2",
        "secondary-fixed-dim": "#a1d1b8",
        "primary-fixed": "#ffdbcf",
        "tertiary-fixed": "#ffdeae",
        "background": "#fef9f0",
        "secondary-container": "#bceed3",
        "surface-container-highest": "#e7e2d9",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#604100",
        "on-tertiary-fixed": "#281900",
        "surface-variant": "#e7e2d9",
        "tertiary-fixed-dim": "#fdba45",
        "on-primary": "#ffffff",
        "tertiary-container": "#956600",
        "on-secondary-fixed": "#002114",
        "on-secondary": "#ffffff",
        "surface-bright": "#fef9f0",
        "surface-container-high": "#ece8df",
        "on-primary-fixed-variant": "#832700",
        "surface-dim": "#ded9d1",
        "error": "#ba1a1a",
        "tertiary": "#754f00",
        "on-surface": "#1d1c16",
        "secondary": "#3a6752",
        "surface-container-low": "#f8f3ea",
        "inverse-surface": "#32302a",
        "surface": "#fef9f0",
        "primary-fixed-dim": "#ffb59c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xl": "3rem",
        "gutter": "1.5rem",
        "margin-mobile": "1.25rem",
        "space-lg": "1.75rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin": "3rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        body: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        headline: ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-sm": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "display-lg-mobile": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-sm": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-md": ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "title-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["var(--font-playfair)", "Playfair Display", "serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
